<a href="https://colab.research.google.com/github/arnoldsanroque/Linear-Algebra_2nd-Sem/blob/main/Assignment5_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra

## Laboratory 3: Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of
matrices, we'll try to the same operations with matrices and even more.

# Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations
3. Apply matrix algebra in engineering solutions.

# Discussion

Before working on matrices using Python programming language, we need to import first a python library called, NumPy or Numerical Python. NumPy is used when working with arrays, in other words, it has functions when working with matrices [1]. Importing matplotlib.pyplot is also needed since it will enable the researchers to make matplotlib work like MATLAB where its functions make some changes to a certain figure or a plotting area [2]. The %matplotlib inline is also declared first because this is responsible for the line plots when the codes are run [3]. 

In [187]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

According to Cuemath [4], the transposition of the matrix in linear algebra is obtained by changing the rows into columns and columns into rows. This method is crucial, especially in solving systems of equations regarding the inverse of a matrix and also in estimating variances in regression. So for a matrix A its
transpose is denoted as $A^T$. So for example: 

$$ 
A=\begin{bmatrix} 1 & 2 & 5 \\ 5 & -1 & 0 \\ 0 & -3 & 3\end{bmatrix}
$$

$$ 
A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}
$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [184]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [185]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [189]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [190]:
np.array_equiv(AT1, AT2)

True

In [191]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [192]:
np.transpose(B).shape

(4, 2)

In [193]:
B.T.shape

(4, 2)

## Dot Product / Inner Product

A dot product is an algebraic operation that is computed using two equal-sized vectors resulting in one scalar value [5]. Just like its definition, the dot product or inner product in the Python programming language is an algebraic operation between two arrays or matrices. However, the dot product of vectors is one-dimensional meaning there are fewer restrictions than the dot product of matrices. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [194]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [195]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [196]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [197]:
X @ Y

array([[3, 4],
       [2, 2]])

In [198]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

Given a matrix A with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

In this case, $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that are eligible to perform dot product is matrices $A$ and $C$ or $B$ and $C$.


In [199]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [227]:
A @ C

array([[106,  82,  92],
       [173, 130, 153],
       [116, 113, 118]])

In [201]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

It is noticeable that the shape of the dot product changed and its shape is not the same as any of the matrices used. The shape of a dot product is derived from the shapes of the matrices used. Recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A$ dot $B$ should have a shape of $(a,c)$.


In [202]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [203]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [204]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

### Rule 2: Dot Product has special properties
Dot products are prevalent in matrix algebra, this implies that it has several unique properties and should be considered when formulating solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [206]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,0]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [207]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [208]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [209]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [210]:
np.array_equal(a_dot_z,z_mat)

True

In [211]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

In matrices, determinants scalar values that is calculated from a square matrix. It helps to solve inverses of matrices, systems of linear equations, calculus, etc [6]. 

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

The representation is not limited to 2x2 matrices. This problem can be solved by using several methods such as co-factor expansion and the minors method. To solve this programmatically, the code `np.linalg.det()` is used.

In [212]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [213]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

## Inverse

The inverse of a matrix is a fundamental operation in matrix algebra wherein the given matrix gives a multiplicative identity of a matrix [7]. The inverse of a matrix determines the matrix’s solvability and characteristics as a system of linear equations.

Now to determine the inverse of a matrix we need to perform several steps. 

So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$

For higher-dimension matrices, co-factors, minors, adjugates, and other reduction techniques are used. To solve this programmatically, the code `np.linalg.inv()` is used.

In [214]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [215]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matrix that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [216]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

## Activity

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [217]:
A = np.array([
    [2,4,6],
    [5,7,8],  
    [4,2,9]  
])

B = np.array([
   [7,4,9],
   [15,6,8],  
   [14,22,5]            
])

C = np.array([
    [5,6,8],
    [12,4,7], 
    [8,9,8]
])

In [218]:
# Commutative Property (First Property)
print("The First Property states A*B is Not Equal to B*A")
print()

print("Matrix A: \n{}".format(A))
print()
print("Matrix B: \n{}".format(B))
print()

x = A@B
print("A@B\n\n{}".format(x))
print()
y = B@A
print("B@A\n\n{}".format(y))
print()

a = np.array_equiv(x,y)
print("Is A@B equal to B@A? \n")
print(a)

The First Property states A*B is Not Equal to B*A

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Matrix B: 
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

A@B

[[158 164  80]
 [252 238 141]
 [184 226  97]]

B@A

[[ 70  74 155]
 [ 92 118 210]
 [158 220 305]]

Is A@B equal to B@A? 

False


In [219]:
# Associative Property (Second Property)
print("The Second Property states A@(B@C) = (A@B)@C")
print()

print("Matrix A: \n{}".format(A))
print()
print("Matrix B: \n{}".format(B))
print()
print("Matrix C: \n{}".format(C))
print()

x = A@(B@C)
print("A@(B@C)\n\n{}".format(x))
print()
y = (A@B)@C
print("(A@B)@C\n\n{}".format(y))
print()

a = np.array_equiv(x,y)
print("Is the Associative Property True? \n")
print(a)


The Second Property states A@(B@C) = (A@B)@C

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Matrix B: 
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

Matrix C: 
[[ 5  6  8]
 [12  4  7]
 [ 8  9  8]]

A@(B@C)

[[3398 2324 3052]
 [5244 3733 4810]
 [4408 2881 3830]]

(A@B)@C

[[3398 2324 3052]
 [5244 3733 4810]
 [4408 2881 3830]]

Is the Associative Property True? 

True


In [220]:
# Distributive Property #1 (Third Property)
print("The Third Property states A@(B+C) = A@B + A@C")
print()

print("Matrix A: \n{}".format(A))
print()
print("Matrix B: \n{}".format(B))
print()
print("Matrix C: \n{}".format(C))
print()

x = A@(B+C)
print("A@(B+C)\n\n{}".format(x))
print()
y = A@B + A@C
print("A@B + A@C\n\n{}".format(y))
print()

a = np.array_equiv(x,y)
print("Is the First Distributive Property True? \n")
print(a)

The Third Property states A@(B+C) = A@B + A@C

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Matrix B: 
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

Matrix C: 
[[ 5  6  8]
 [12  4  7]
 [ 8  9  8]]

A@(B+C)

[[264 246 172]
 [425 368 294]
 [300 339 215]]

A@B + A@C

[[264 246 172]
 [425 368 294]
 [300 339 215]]

Is the First Distributive Property True? 

True


In [221]:
# Distributive Property #2 (Fourth Property)
print("The Fourth Property states (B+C)@A = B@A + C@A")
print()

print("Matrix A: \n{}".format(A))
print()
print("Matrix B: \n{}".format(B))
print()
print("Matrix C: \n{}".format(C))
print()

x = (B+C)@A
print("(B+C)@A\n\n{}".format(x))
print()
y = B@A + C@A
print("B@A + C@A\n\n{}".format(y))
print()

a = np.array_equiv(x,y)
print("Is the Second Distributive Property True? \n")
print(a)

The Fourth Property states (B+C)@A = B@A + C@A

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Matrix B: 
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

Matrix C: 
[[ 5  6  8]
 [12  4  7]
 [ 8  9  8]]

(B+C)@A

[[142 152 305]
 [164 208 377]
 [251 331 497]]

B@A + C@A

[[142 152 305]
 [164 208 377]
 [251 331 497]]

Is the Second Distributive Property True? 

True


In [222]:
# Identity Property (Fifth Property)
print("The Fifth Property states A@I = A")
print()

I = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
print("I:\n{}".format(I))
print()
print("Matrix A: \n{}".format(A))
print()

x = A@I 
print("A@I \n{}".format(x))
print()
y = A

a = np.array_equiv(x,y)
print("Is the Identity Property Correct?\n")
print(a)

The Fifth Property states A@I = A

I:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

A@I 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

Is the Identity Property Correct?

True


In [223]:
# Null Property (Sixth Property)
print("The Sixth Property states A@0 = 0")
print()

Z = np.zeros((3,3))
print("Z:\n{}".format(Z))
print()
print("Matrix A: \n{}".format(A))
print()

x = A@Z 
print("A@Z \n{}".format(x))
print()
y = A

a = np.array_equiv(x,y)
print("Does A@Z possess any values other than an array of zeroes?\n")
print(a)

The Sixth Property states A@0 = 0

Z:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix A: 
[[2 4 6]
 [5 7 8]
 [4 2 9]]

A@Z 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Does A@Z possess any values other than an array of zeroes?

False


## Conclusion

  The fundamentals of matrix operations are the ones being focused on in this laboratory report. Transposition, Dot Product, Determinants, and Inverses of matrices are thoroughly discussed as well as the methods used to perform the operations. The importance of these operations has been known as the report continues. Transpositions are important in finding regressions like variances and covariances for the interpretation of data. Dot products are also used in interpreting data that has been gathered by researchers. Finding the determinants is useful in solving linear equations, capturing the transformations of the change in area and volume of a certain material, and changing the variables of an integral. It has been observed that there is no division of matrices and the authors of this laboratory report think that this is where the importance of the inverses of matrices comes in. Moreover, inverses of matrices can also help solve systems of linear equations. With these observations and realizations, the importance of the said operations of matrices has been known. The collection and analysis of a series of matrices lay the groundwork for systematic change in patient care and medical education, as well as providing a rich supply of data for operational and improvement research.
