<a href="https://colab.research.google.com/github/arnoldsanroque/Linear-Algebra_2nd-Sem/blob/main/Laboratory_2_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 2: Matrices

### Objectives
At the end of this activity you will be able to
1.   Be familiar with matrices and their relation to linear equations.
2.   Perform basic matrix operations.
3.   Program and translate matrix equations and 
operations using Python.





# Discussion


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline 

## Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them. 

***A***, ***B***, and ***C*** as systems of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x +y + z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        12x + 21y+ 18z \\ 
        10x - 10y -18z \\
        -6x + 27y +7z
    \end{array}
\right. 
$$


We could see that ***A*** is a system of 2 equations with 2 parameters. ***B*** is a system of 3 equations with 3 parameters. And ***C*** is a system of 4 equations with 4 parameters. We can represent them as matrices:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 12 & 7 & 6 \\ 1 & 4 & -3 \\ -10 & 6 & -5\end{bmatrix}
$$


### Declaring Matrices

The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be represented just like the equation below. Whereas ***A*** is a matrix consisting of elements denoted by **a**i,j*. Denoted by *i* is the number of rows in the matrix while *j* stands for the number of columns.
Do note that the size of a matrix is *i x j*.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [50]:
def describe_mat(matrix) :
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [51]:
## Declaring a 2 x 2 matrix
A = np.array ([
    [1,2],
    [3,1]
])
describe_mat(A)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [52]:
## Declaring a 2 x 3 matrix
G = np.array([
    [65, 44, 97],
    [83, 41, 74]
])
describe_mat(G)

Matrix:
[[65 44 97]
 [83 41 74]]

Shape:	(2, 3)
Rank:	2



In [53]:
## Declaring a 3 x 2 matrix
G = np.array([
    [65, 44],
    [83, 41],
    [97, 74]
])
describe_mat(G)

Matrix:
[[65 44]
 [83 41]
 [97 74]]

Shape:	(3, 2)
Rank:	2



In [54]:
L = np.array([12, 3, 34, 54, 7, 432, 32, 56])
describe_mat(L)

Matrix:
[ 12   3  34  54   7 432  32  56]

Shape:	(8,)
Rank:	1



## Categorizing Matrices 

There are several ways of classifying matrices. One could be 
according to their **shape** and another is according to their element values. We'll try to go through them.

### According to Shape 

According to shape - it defines the number of rows and columns of the specific matrix

In [63]:
A = np.array ([
    [1,2],
    [3,1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2
Is Square: True



### Row and Column Matrices

A 1-by-n matrix (a single row) is a row matrix, while an n-by-1 matrix is a column matrix (a single column). The terms "row and column matrices" and "row and column vectors" are interchangeable.

In [65]:
## Declaring a Row Matrix

row_mat_1D = np.array([
     [1, 2, 3, 4, 5]                  
]) 
row_mat_2D = np.array([
     [6, 7, 8, 9, 10]                  
]) 
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[[1 2 3 4 5]]

Shape:	(1, 5)
Rank:	2
Is Square: False

Matrix:
[[ 6  7  8  9 10]]

Shape:	(1, 5)
Rank:	2
Is Square: False



In [66]:
## Declaring a Column Matrix

col_mat =np.array([
     [2], 
     [12],
     [18],
     [10],
     [7],
     [21]             
])
describe_mat(col_mat)

Matrix:
[[ 2]
 [12]
 [18]
 [10]
 [ 7]
 [21]]

Shape:	(6, 1)
Rank:	2
Is Square: False



### Square Matrices

A square matrix is a matrix with the exact number of components as its name suggests. Its order is of the form n x n since it contains an equal number of rows and columns. All matrix operations such as transpose, determinant, adjoint, and inverse and matrices' mathematical operations apply to a square matrix.

In [72]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nshape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [74]:
square_mat = np.array([
   [2,4,6],
   [5,7,8],  
   [4,2,9]            
])

non_square_mat = np.array([
   [2,4,6],    
   [5,7,8]                    
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[2 4 6]
 [5 7 8]
 [4 2 9]]

shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[2 4 6]
 [5 7 8]]

shape:	(2, 3)
Rank:	2
Is Square: False



# According to Element Values

According to element values - it defines what kind of matrix it will be, it can be square, null, zero, ones, diagonal, identity, upper triangular, and lower triangular matrix.

## Null Matrix

A Null Matrix is a matrix in which each element is none. The null matrix, often known as a zero matrix, has a variable number of rows and columns. Because adding a null matrix to any other matrix produces the same outcome, a null matrix is also known as the additive identity of the provided matrix.

In [75]:
def describe_mat(matrix) :
  if matrix.size > 0 :
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else :
    print('Matrix is Null')


In [76]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix

A zero matrix is one in which most elements are equal to zero. A zero matrix is represented by 0, and if necessary, a subscript can be applied to specify the matrix's dimensions. Zero matrices play a similar role in matrices operations as zero does in real-number operations.

In [77]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Ones Matrix

A matrix of ones, also known as an all-ones matrix, is a matrix in which all of the elements are equal to one.

In [78]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Diagonal Matrix

A diagonal matrix has both upper and bottom triangle elements. The name "diagonal matrix" comes from all the entries above and below the principal diagonal are zeros.

In [79]:
np.array([
   [4,0,0,0],
   [0,6,0,0],
   [0,0,7,0],
   [0,0,0,2]       
])

array([[4, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 2]])

In [80]:
d = np.diag([2, 3, 5, 7])
d.shape[0] == d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [81]:
a = np.diag([2, 3, 5, 7])
np.diag(a).shape == a.shape[1] == a.shape[4]

False

## Identity Matrix

An identity matrix is a square matrix for all primary diagonal elements and zeros for all other elements. The letter "In" or simply "I" is used to indicate it. The result of multiplying any matrix by the identity matrix is the provided matrix.

In [82]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Upper Triangular Matrix

All of the entries below the main diagonal are zero in the upper triangular matrix.

In [84]:
np.array([
   [1, 2, 3, 4],
   [0, 5, 6, 7],
   [0, 0, 8, 9],
   [0, 0, 0, 10]      
])

array([[ 1,  2,  3,  4],
       [ 0,  5,  6,  7],
       [ 0,  0,  8,  9],
       [ 0,  0,  0, 10]])

## Lower Triangular Matrix

All of the entries above the main diagonal are zero in the lower triangular matrix.

In [85]:
np.array([
   [10, 0, 0, 0],       
   [8, 9, 0, 0],
   [5, 6, 7, 0],
   [1, 2, 3, 4],     
])

array([[10,  0,  0,  0],
       [ 8,  9,  0,  0],
       [ 5,  6,  7,  0],
       [ 1,  2,  3,  4]])

# Practice Problems

1. Given the linear combination below, try to create a corresponding matrix representing it.


$$\theta = 5x + 3y - z$$


**Answer:**

$$
\theta = \begin{bmatrix} 5 & 3 & -1 \end{bmatrix} \\
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


**Answer:**
$$
A=\begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix} \\
$$

3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [86]:
G = np.array([ 
        [1,7,8], 
        [2,2,2], 
        [4,6,7] 
])

**Answer:**
$$
G = \left\{\begin{array}
5x + 7y + 8z\\
2x + 2y + 2z\\
4x + 6y + 7z
\end{array}\right.
$$


$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix} \\
$$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [87]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

**Answer:**
$$
H = \left\{\begin{array}
1x\\
2x + 2y\\
4x + 6y + 7z
\end{array}\right.
$$


$$
H=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix} \\
$$

## Matrix Algebra

Matrix algebra is used to display graphs, calculate statistics, and conduct scientific investigations and research in various domains. Matrices may also be used to represent real-world information such as population, infant mortality rate, etc. For charting surveys, these are the finest representation approaches.

## Addition

The operation of combining the entries of two matrices is known as matrix addition.

In [88]:
A = np.array([
    [12, 3],     
    [4, 65],
    [74, 28]
])
B = np.array([
    [89, 90],     
    [4, 5],
    [6, 7]      
])
A+B

array([[101,  93],
       [  8,  70],
       [ 80,  35]])

In [89]:
## Broadcasting
# 2*np.ones(A.shape)+A
6 + A

array([[18,  9],
       [10, 71],
       [80, 34]])

## Subtraction

Subtraction between two matrices is achievable if their order or dimensions are the same. To subtract two or more matrices, they must have the same number of rows and columns.

In [90]:
A - B

array([[-77, -87],
       [  0,  60],
       [ 68,  21]])

In [91]:
7 - A

array([[ -5,   4],
       [  3, -58],
       [-67, -21]])

In [92]:
5-B == 5*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## Element-Wise Multiplication

Element-Wise Multiplication is an operation of multiplying two numbers but only for its corresponding element.

In [93]:
A*B
np.multiply(A,B)

array([[1068,  270],
       [  16,  325],
       [ 444,  196]])

In [94]:
2*A

array([[ 24,   6],
       [  8, 130],
       [148,  56]])

# Activity

## Task #1

Create a function named mat_desc() that througouhly describes a matrix, it should:
Displays the shape, size, and rank of the matrix. Displays whether the matrix is square or non-square. Displays whether the matrix is an empty matrix. Displays if the matrix is an identity, ones, or zeros matrix Use 5 sample matrices in which their shapes are not lower than . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [95]:
def mat_desc (matrix):
  if matrix.size > 0:
    if matrix.shape [0] == matrix.shape[1]:
      m = "Square."
    else:
      m = "Non-square."
    if np.all(matrix == np.identity(matrix.shape[0])):
      mp = "Identity Matrix."
    elif np.all(matrix == np.zeros(matrix.shape)):
      mp = "Zero Matrix."
    elif np.all(matrix == np.ones(matrix.shape)):
      mp = "Ones Matrix."
    else:
      mp = "None."
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize: \t{matrix.size}\nRank:\t{matrix.ndim}\nSquare?: {m}\nSpecial Characteristics: {mp}')
  else:
    print('Matrix is Empty')

In [96]:
square_mat = np.array([
   [7,4,9],
   [15,6,8],  
   [14,22,5]            
])

non_square_mat = np.array([
   [4,7,12],    
   [3,4,18],
   [33,44,76], 
   [23,34,55]                  
])
mat_desc(square_mat)
mat_desc(non_square_mat)

Matrix:
[[ 7  4  9]
 [15  6  8]
 [14 22  5]]

Shape:	(3, 3)
Size: 	9
Rank:	2
Square?: Square.
Special Characteristics: None.
Matrix:
[[ 4  7 12]
 [ 3  4 18]
 [33 44 76]
 [23 34 55]]

Shape:	(4, 3)
Size: 	12
Rank:	2
Square?: Non-square.
Special Characteristics: None.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  import sys


In [97]:
square_mat = np.array([
   [72,5,29,17],
   [11,16,32,45],  
   [12,32,16, 24]            
])

non_square_mat = np.array([
   [42,67,25, 23],    
   [35,14,19, 29], 
   [15,17,69, 45],  
   [75,77,99, 85],                 
])
mat_desc(square_mat)
mat_desc(non_square_mat)

Matrix:
[[72  5 29 17]
 [11 16 32 45]
 [12 32 16 24]]

Shape:	(3, 4)
Size: 	12
Rank:	2
Square?: Non-square.
Special Characteristics: None.
Matrix:
[[42 67 25 23]
 [35 14 19 29]
 [15 17 69 45]
 [75 77 99 85]]

Shape:	(4, 4)
Size: 	16
Rank:	2
Square?: Square.
Special Characteristics: None.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  import sys


In [98]:
square_mat = np.array([
   [44,43,34,77,85],
   [21,18,33,44,97],  
   [72,42,66,55,82],
   [25,27,88,99,75],
   [45,37,98,19,15],           
])

non_square_mat = np.array([
   [72,77,25, 63],    
   [75,13,10, 89],
   [65,23,80, 79]                    
])
mat_desc(square_mat)
mat_desc(non_square_mat)

Matrix:
[[44 43 34 77 85]
 [21 18 33 44 97]
 [72 42 66 55 82]
 [25 27 88 99 75]
 [45 37 98 19 15]]

Shape:	(5, 5)
Size: 	25
Rank:	2
Square?: Square.
Special Characteristics: None.
Matrix:
[[72 77 25 63]
 [75 13 10 89]
 [65 23 80 79]]

Shape:	(3, 4)
Size: 	12
Rank:	2
Square?: Non-square.
Special Characteristics: None.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  import sys


## Identity, Ones, Zero Or Empty Matrix

### Null Matrix or Empty Matrix

In [99]:
null_mat = np.array([])
mat_desc(null_mat)


Matrix is Empty


### Zero Matrix

In [100]:
zero_mat = np.array([
   [0,0,0,0],
   [0,0,0,0],  
   [0,0,0,0],
   [0,0,0,0]          
])
mat_desc(zero_mat)

Matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Shape:	(4, 4)
Size: 	16
Rank:	2
Square?: Square.
Special Characteristics: Zero Matrix.


### Ones Matrix

In [101]:
ones_mat = np.array([
   [1,1,1,1,1],
   [1,1,1,1,1],
   [1,1,1,1,1],
   [1,1,1,1,1],
   [1,1,1,1,1],          
])
mat_desc(ones_mat)

Matrix:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Shape:	(5, 5)
Size: 	25
Rank:	2
Square?: Square.
Special Characteristics: Ones Matrix.


### Identity Matrix

In [102]:
identity_mat = np.array([
   [1., 0., 0., 0., 0., 0., 0., 0.],
   [0., 1., 0., 0., 0., 0., 0., 0.],
   [0., 0., 1., 0., 0., 0., 0., 0.],
   [0., 0., 0., 1., 0., 0., 0., 0.],
   [0., 0., 0., 0., 1., 0., 0., 0.],
   [0., 0., 0., 0., 0., 1., 0., 0.],
   [0., 0., 0., 0., 0., 0., 1., 0.],
   [0., 0., 0., 0., 0., 0., 0., 1.]        
])
mat_desc(identity_mat)

Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

Shape:	(8, 8)
Size: 	64
Rank:	2
Square?: Square.
Special Characteristics: Identity Matrix.


## Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your 
 own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the different of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.
Use 5 sample matrices in which their shapes are not lower than . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [103]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:\n', mat1)
    print()
    print('Matrix 2:\n', mat2)
    print()
    if(mat1.shape != mat2.shape):
        print('Since the shape of both matrices are not the same, we could not perform the operations.')
        return
    print('Sum of the given matrices:')
    print()
    Addition = mat1 + mat2
    print(Addition)
    print()
    print('Difference of the given matrices:')
    print()
    Subtraction = mat1 - mat2
    print(Subtraction)
    print()
    print('Element-wise multiplication product of the given matrices:')
    print()
    EW_Multiplication = np.multiply(mat1, mat2)
    print(EW_Multiplication)
    print()
    print('Element-wise division quotient of the given matrices:')
    print()
    EW_Division = np.divide(mat1, mat2)
    print(EW_Division)

In [104]:
print('Sample 1:\n')
mat_operations([[7,4,6], [5,4,7], [1,3,9]], [[6,2,6],[8,4,1],[7,2,1]])

print()
print()

print('Sample 2:\n')
mat_operations([[4, 6, 6,1], [8,3,8,5], [2,1,3,9]], [[7,3,2,8],[4,7,4,2],[9,7,0,5]])

print()
print()

print('Sample 3:\n')
mat_operations([[3,8,0], [5,8,4], [8,1,4]], [[2,4,5],[3,5,9],[1,2,8]])

print()
print()

print('Sample 4:\n')
mat_operations([[4,2,1,6], [3,5,0,9]], [[8,4,3,7,0],[1,2,3,4,5],[6,7,8,9,10]])

print()
print()

print('Sample 5:\n')
mat_operations([[4,7,5,3,2,1], [8,3,6,5,9,7], [5,1,4,7,3,1]], [[9,3,6,8,3,2],[8,9,3,5,4,3],[4,6,9,2,1,1]])

Sample 1:

Matrix 1:
 [[7 4 6]
 [5 4 7]
 [1 3 9]]

Matrix 2:
 [[6 2 6]
 [8 4 1]
 [7 2 1]]

Sum of the given matrices:

[[13  6 12]
 [13  8  8]
 [ 8  5 10]]

Difference of the given matrices:

[[ 1  2  0]
 [-3  0  6]
 [-6  1  8]]

Element-wise multiplication product of the given matrices:

[[42  8 36]
 [40 16  7]
 [ 7  6  9]]

Element-wise division quotient of the given matrices:

[[1.16666667 2.         1.        ]
 [0.625      1.         7.        ]
 [0.14285714 1.5        9.        ]]


Sample 2:

Matrix 1:
 [[4 6 6 1]
 [8 3 8 5]
 [2 1 3 9]]

Matrix 2:
 [[7 3 2 8]
 [4 7 4 2]
 [9 7 0 5]]

Sum of the given matrices:

[[11  9  8  9]
 [12 10 12  7]
 [11  8  3 14]]

Difference of the given matrices:

[[-3  3  4 -7]
 [ 4 -4  4  3]
 [-7 -6  3  4]]

Element-wise multiplication product of the given matrices:

[[28 18 12  8]
 [32 21 32 10]
 [18  7  0 45]]

Element-wise division quotient of the given matrices:

[[0.57142857 2.         3.         0.125     ]
 [2.         0.42857143 2.         2.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:28: RuntimeWarning: divide by zero encountered in true_divide
